// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wefwkfmxdyzgyrzcknrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZndrZm14ZHl6Z3lyemNrbnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDgwNzgsImV4cCI6MjA1ODY4NDA3OH0.wsWJQvFDnLsBaMDChmqk4cDaoLwBHH52NJTdQu-ImzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);